---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rmdref

<!-- badges: start -->
<!-- badges: end -->

The goal of rmdref is to help manage reference files for Rmarkdown.

## Installation

You can install the development version of rmdref like so:

``` r
remotes::install("joelnitta/rmdref")
```

## Examples

Extract citation keys (beginning with `@`) from an Rmd file (or files):

```{r extract-example}
library(rmdref)

# Write an example Rmd to a temporary file
tempfile <- tempfile(fileext = ".Rmd")
lines <- c(
  "---",
  "title: 'Report'",
  "output_format: html_document",
  "---",
  "This statement is supported by @Nitta2021",
  "[@Foo1983; @Blah2001; but see @Smith2020]."
)
write(lines, tempfile)

# Extract citations
extract_citations(tempfile)

# Cleanup
file.remove(tempfile)
```

More examples to come soon...

## License

[MIT](LICENSE.md)
